<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classmodule extends \Application\Entity\Classmodule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'pkCcid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'iscore', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'examweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'cwkweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkGroupid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'parentid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkModuleid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkPeriodid');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'pkCcid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'iscore', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'examweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'cwkweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkGroupid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'parentid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkModuleid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkPeriodid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classmodule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkCcid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkCcid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkCcid', array());

        return parent::getPkCcid();
    }

    /**
     * {@inheritDoc}
     */
    public function setIscore($iscore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIscore', array($iscore));

        return parent::setIscore($iscore);
    }

    /**
     * {@inheritDoc}
     */
    public function getIscore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIscore', array());

        return parent::getIscore();
    }

    /**
     * {@inheritDoc}
     */
    public function setExamweight($examweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExamweight', array($examweight));

        return parent::setExamweight($examweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamweight', array());

        return parent::getExamweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setCwkweight($cwkweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCwkweight', array($cwkweight));

        return parent::setCwkweight($cwkweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCwkweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCwkweight', array());

        return parent::getCwkweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkGroupid(\Application\Entity\Programgroup $fkGroupid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkGroupid', array($fkGroupid));

        return parent::setFkGroupid($fkGroupid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkGroupid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkGroupid', array());

        return parent::getFkGroupid();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentid(\Application\Entity\Classmodule $parentid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentid', array($parentid));

        return parent::setParentid($parentid);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentid', array());

        return parent::getParentid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkModuleid(\Application\Entity\Module $fkModuleid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkModuleid', array($fkModuleid));

        return parent::setFkModuleid($fkModuleid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkModuleid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkModuleid', array());

        return parent::getFkModuleid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkPeriodid(\Application\Entity\Academicperiod $fkPeriodid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkPeriodid', array($fkPeriodid));

        return parent::setFkPeriodid($fkPeriodid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkPeriodid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkPeriodid', array());

        return parent::getFkPeriodid();
    }

}
