<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Assessmentitem extends \Application\Entity\Assessmentitem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'pkAiid', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'createdon', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'assessmentTitle', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'weighting', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'shortName', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'fkAtid', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'fkStaffid', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'fkCcid');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'pkAiid', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'createdon', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'assessmentTitle', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'weighting', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'shortName', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'fkAtid', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'fkStaffid', '' . "\0" . 'Application\\Entity\\Assessmentitem' . "\0" . 'fkCcid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Assessmentitem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkAiid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkAiid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkAiid', array());

        return parent::getPkAiid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedon($createdon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedon', array($createdon));

        return parent::setCreatedon($createdon);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedon', array());

        return parent::getCreatedon();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssessmentTitle($assessmentTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssessmentTitle', array($assessmentTitle));

        return parent::setAssessmentTitle($assessmentTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssessmentTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssessmentTitle', array());

        return parent::getAssessmentTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeighting($weighting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeighting', array($weighting));

        return parent::setWeighting($weighting);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeighting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeighting', array());

        return parent::getWeighting();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortName($shortName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortName', array($shortName));

        return parent::setShortName($shortName);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortName', array());

        return parent::getShortName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAtid(\Application\Entity\Assessmenttype $fkAtid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAtid', array($fkAtid));

        return parent::setFkAtid($fkAtid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAtid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAtid', array());

        return parent::getFkAtid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkStaffid(\Application\Entity\Staff $fkStaffid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkStaffid', array($fkStaffid));

        return parent::setFkStaffid($fkStaffid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkStaffid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkStaffid', array());

        return parent::getFkStaffid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkCcid(\Application\Entity\Classmodule $fkCcid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkCcid', array($fkCcid));

        return parent::setFkCcid($fkCcid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCcid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCcid', array());

        return parent::getFkCcid();
    }

}
