<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Application\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'pkUserid', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'ipaddress', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'passwordlastchanged', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'logintimes', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastlogindate', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastloginip', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'logindate', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'accounttype', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstname', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'surname', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'title', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'gender', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'othernames', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'emailaddress', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'fkRoleid');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'pkUserid', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'username', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'password', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'ipaddress', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'passwordlastchanged', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'logintimes', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastlogindate', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastloginip', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'logindate', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'accounttype', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstname', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'surname', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'title', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'gender', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'othernames', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'emailaddress', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'fkRoleid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkUserid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkUserid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkUserid', array());

        return parent::getPkUserid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setIpaddress($ipaddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIpaddress', array($ipaddress));

        return parent::setIpaddress($ipaddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getIpaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIpaddress', array());

        return parent::getIpaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordlastchanged($passwordlastchanged)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordlastchanged', array($passwordlastchanged));

        return parent::setPasswordlastchanged($passwordlastchanged);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordlastchanged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordlastchanged', array());

        return parent::getPasswordlastchanged();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogintimes($logintimes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogintimes', array($logintimes));

        return parent::setLogintimes($logintimes);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogintimes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogintimes', array());

        return parent::getLogintimes();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastlogindate($lastlogindate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastlogindate', array($lastlogindate));

        return parent::setLastlogindate($lastlogindate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastlogindate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastlogindate', array());

        return parent::getLastlogindate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastloginip($lastloginip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastloginip', array($lastloginip));

        return parent::setLastloginip($lastloginip);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastloginip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastloginip', array());

        return parent::getLastloginip();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogindate($logindate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogindate', array($logindate));

        return parent::setLogindate($logindate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogindate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogindate', array());

        return parent::getLogindate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccounttype($accounttype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccounttype', array($accounttype));

        return parent::setAccounttype($accounttype);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccounttype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccounttype', array());

        return parent::getAccounttype();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', array($surname));

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', array());

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthernames($othernames)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthernames', array($othernames));

        return parent::setOthernames($othernames);
    }

    /**
     * {@inheritDoc}
     */
    public function getOthernames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthernames', array());

        return parent::getOthernames();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailaddress($emailaddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailaddress', array($emailaddress));

        return parent::setEmailaddress($emailaddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailaddress', array());

        return parent::getEmailaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkRoleid(\Application\Entity\Role $fkRoleid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkRoleid', array($fkRoleid));

        return parent::setFkRoleid($fkRoleid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkRoleid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkRoleid', array());

        return parent::getFkRoleid();
    }

}
