<script type="text/javascript">
    var is_xmlhttprequest = <?php echo $is_xmlhttprequest; ?>;
    var urlform           = '<?php echo $this->url($controller, array('action'=>$confirmaction)); ?>';
</script>
<div id="confirmmodal" class="modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
  <?php
  $form->setAttributes(array('name'=>'formsubmit'));
  echo $this->form()->openTag($form);
 
  ?>
    <div class="modal-dialog modal-body">
        
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="formtitle">Confirm<span id="user"></span></h4>
        </div>
        <div class="modal-body">
            <div class="alert alert-info" role="alert">
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                <span id="description">This action will delete the item with its corresponding marks. Are you sure you want to continue ? </span>
              </div>
            <div id="progress"><center></center></div>
            <div class="alert alert-success" title="success" id="success" role="alert"></div>
            <div class="alert alert-danger" title="warning" id="warning" role="alert">
                <span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>
            </div>
            
            <div>
                <input name="itemid" value="" type="hidden" />
                <input name="periodid" value="" type="hidden" />
            </div>
        </div>
       <div class="modal-footer">
           <button name="btnSave" value="1" id="btnSave" class="btn btn-primary ">&nbsp;Continue</button>
           <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>
           
      </div>
    </div>
  </div>
 <?php
 echo $this->form()->closeTag();
 ?>
    
</div>