<nav class="navbar navbar-submenu">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li class="#"><a href="<?php echo $this->url("administration",array("action"=>"academicperiod")); ?>">Academic session</a></li>
                    
                    <li><a href="<?php echo $this->url("administration",array("action"=>"users")); ?>">Manage Users / Groups</a></li>
                    <li><a href="#">System preferences</a></li>
                    <li><a href="#">Change semester</a></li>
                    <li><a href="#">Course/module bank</a></li>
                    <li><a href="<?php echo $this->url("administration",array("action"=>"faculties")); ?>">Manage faculty</a></li>
                    <li><a href="#">Reports</a></li>
                  </ul>
                </div>
            </nav>