<nav class="navbar navbar-submenu">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                        
                  </button>

                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                  <ul class="nav navbar-nav">
                    <li class="#"><a href="<?php echo $this->url("examination",array("action"=>"index")); ?>">Assessments</a></li>
                    
                    <li><a href="#">My results</a></li>
                    <li><a href="#">Sign offs</a></li>
                    <li><a href="#">Exam management</a></li>
                    <li><a href="#">Lecturer-Course Allocation</a></li>
                    <li><a href="#">Student-Course Assignment</a></li>
                    <li><a href="#">Reports</a></li>
                  </ul>
                </div>
            </nav>