<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SMIS '. $this->translate(' v 2.0'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/mtree.css'))
                        ->prependStylesheet($this->basePath('css/custom.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
           
        ; ?>

    </head>
    <body>
    <div class="container-fluid main-wrap">
        <div class="row header-wrap">
            <div class="col col-md-12">
                <div class="navbar-header"><img src="<?php echo $this->basePath(); ?>/img/logo.png" alt="" class="img-responsive"></div>
                <?php
                if($this->identity()){
                ?>
                <ul class="nav navbar-nav navbar-right user-wrap">
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#"><?php echo $this->identity()->getFirstname(); ?> <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Change password</a></li>
                        <li><a href="<?php echo $this->url("home",array("action"=>"logout")); ?>">Logout</a></li>
                      </ul>
                    </li>
                    <li><img src="<?php echo $this->basePath(); ?>/img/placeholder.jpe" alt="" height="70px" class="img-circle"></li>
                </ul>
                <?php
                }
                ?>
            </div>  
        </div>

        <?php
        if($this->identity() && $this->activemodule != "login"){
            echo $this->partial("include/menu/main.phtml");
        }else{
            echo "<p />";
        }
        echo $this->content;
        ?>
        
    <div class="row footer-wrap">
        <div class="col col-md-6">
            &copy; Copyright <?php echo date('Y'); ?> - Poly SMIS V. 02 .
</div>
</div>                
</div>
<?php echo $this->headScript()
            ->prependFile($this->basePath('js/mtree.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>
</body>
</html>
