<div class="row">
    <div class="col col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                
                <div class="menu">
                    <ul class="mtree transit">
    <li><a href="#">BIS</a>
      <ul>
        <li><a href="#">BIS 1</a></li>
        <li><a href="#">BIS 2</a></li>
        <li><a href="#">BIS 3</a></li>
        <li><a href="#">BIS 4</a></li>
        <li><a href="#">Mauritania</a></li>
        <li><a href="#">South Africa</a></li>
      </ul>
    </li>
    <li><a href="#">BIT</a>
      <ul>
        <li><a href="#">North-America</a>
          <ul>
            <li><a href="#">Canada</a></li>
            <li><a href="#">USA</a>
              <ul>
                <li><a href="#">New York</a></li>
                <li><a href="#">California</a>
                  <ul>
                    <li><a href="#">Los Angeles</a></li>
                    <li><a href="#">San Diego</a></li>
                    <li><a href="#">Sacramento</a></li>
                    <li><a href="#">San Francisco</a></li>
                    <li><a href="#">Bakersville</a></li>
                  </ul>
                </li>
                <li><a href="#">Lousiana</a></li>
                <li><a href="#">Texas</a></li>
                <li><a href="#">Nevada</a></li>
                <li><a href="#">Montana</a></li>
                <li><a href="#">Virginia</a></li>
              </ul>
            </li>
          </ul>
        </li>
        <li><a href="#">Middle-America</a>
          <ul>
            <li><a href="#">Mexico</a></li>
            <li><a href="#">Honduras</a></li>
            <li><a href="#">Guatemala</a></li>
          </ul>
        </li>
        <li><a href="#">South-America</a>
          <ul>
            <li><a href="#">Brazil</a></li>
            <li><a href="#">Argentina</a></li>
            <li><a href="#">Uruguay</a></li>
            <li><a href="#">Chile</a></li>
          </ul>
        </li>
      </ul>
    </li>
    <li><a href="#">Asia</a>
      <ul>
        <li><a href="#">China</a></li>
        <li><a href="#">India</a></li>
        <li><a href="#">Malaysia</a></li>
        <li><a href="#">Thailand</a></li>
        <li><a href="#">Vietnam</a></li>
        <li><a href="#">Singapore</a></li>
        <li><a href="#">Indonesia</a></li>
        <li><a href="#">Mongolia</a></li>
      </ul>
    </li>
    <li><a href="#">Europe</a>
      <ul>
        <li><a href="#">North</a>
          <ul>
            <li><a href="#">Norway</a></li>
            <li><a href="#">Sweden</a></li>
            <li><a href="#">Finland</a></li>
          </ul>
        </li>
        <li><a href="#">East</a>
          <ul>
            <li><a href="#">Romania</a></li>
            <li><a href="#">Bulgaria</a></li>
            <li><a href="#">Poland</a></li>
          </ul>
        </li>
        <li><a href="#">South</a>
          <ul>
            <li><a href="#">Italy</a></li>
            <li><a href="#">Greece</a></li>
            <li><a href="#">Spain</a></li>
          </ul>
        </li>
        <li><a href="#">West</a>
          <ul>
            <li><a href="#">France</a></li>
            <li><a href="#">England</a></li>
            <li><a href="#">Portugal</a></li>
          </ul>
        </li>
      </ul>
    </li>
</ul>
                     
                    
                </div>

                
            </div>
        </div>
    </div>
        <div class="col col-md-9">
            <div class="panel panel-default">
            <h3 class="page-header">Dashboard</h3>
            <div class="panel-body">
            <div class="col text-right"><a class="btn btn-primary">Add New Item</a>  </div>
            <hr>
<table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
</table>
                <div class="col ">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label for="email">Show:</label>

<select class="form-control">
  <option>10</option>
  <option>20</option>
  <option>30</option>
  <option>50</option>
  <option>100</option>
</select> 
       
          
    </div>

      <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
                 
               </div>
            </div>
                </div>
        </div>
    </div>