<div class="col col-md-10">
    <h3>Account setting</h3>
    <hr>
    <div class="col col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            
            
            <div class="panel-body">
            <?php
            $userform->setAttributes(array('class'=>'form-horizontal','autocomplete'=>'off'))->prepare();
            echo $this->form()->openTag($userform);
            ?>
                
                <fieldset><legend>Change password</legend>
                    <?php echo $this->formHidden($userform->get('Password')->get('pkUserid')->setValue($userid)); ?>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('oldpassword')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('oldpassword')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('oldpassword')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('Password')->get('password')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('Password')->get('password')); ?>
                       </div>
                       <div class="col-sm-4"><?php echo $this->formElementErrors($userform->get('Password')->get('password')); ?></div>
                      
                    </div>
                    <div class="form-group">   
                       <div class="col-sm-3">
                           <?php echo $this->formLabel($userform->get('Password')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-5">
                           <?php echo $this->formElement($userform->get('Password')->get('cpassword')); ?>
                       </div>
                       <div class="col-sm-3">
                           <?php //echo $this->formElement($userform->get('User')->get('initial')); ?>
                       </div>
                      
                    </div>

                   
                    
                    
                </fieldset>
                
                    <div class="form-group">   
                       <div class="col-sm-3"></div>
                       <div class="col-sm-5">
                           <input name="submit" type="submit" class="btn btn-success" value="Change" />
                           <a href="<?php echo $this->url("home",array("action"=>"index")); ?>"  class="btn btn-warning">Cancel</a>
                       </div>
                       <div class="col-sm-4"></div>
                    </div>                            
                <?php
                $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
        