<?php
echo $this->partial('include/form/modalform.phtml');
echo $this->partial('include/form/assignlecturerform.phtml');
?>
<script type="text/javascript">
$(document).ready(function(){
      // If for the first time assign to lecturer form is loading. Hide departments
       $("#servicingdepartment").hide();
       $("#warning-assign").hide();
       $("#success-assign").hide();
       
      $("a[title='modify']").click(function(){
        $("#fkModuleid").attr('readonly','readonly');
        $("select[name='fkModuleid']").val($("#moduleid"+this.id).val());
        $("select[name='parentid']").val($("#parentid"+this.id).val());
        $("input[name='examweight']").val($("#examweight"+this.id).html());
        $("input[name='cwkweight']").val($("#cwkweight"+this.id).html());
        $("input[name='pkCcid']").val($("#id"+this.id).val());
        $("select[name='iscore']").val($("#iscore"+this.id).val());
        
    });
    
    $('#assignmodal').on('hide.bs.modal', function () {
        document.getElementById('formallocate').reset();
        $("#formallocate select").removeAttr("disabled");
        $("#servicingdepartment").hide();
        $("#warning-assign").html("");
        $("#success-assign").html("");
        $("#warning-assign").hide();
        $("#success-assign").hide();
    });
    
    //Assign name to 
    $(".assign").click(function () {
        $("#subjecttitle").html($("#name"+$(this).attr("tabindex")).html());
        $("input[name='fkCcid']").val($("#id"+$(this).attr("tabindex")).val());
        $("select[name='fkStaffid']").val($("#staffid"+$(this).attr("tabindex")).val());
    });
    
    $("#fkStaffid").change(function(){
        if($(this).val() == "DEPARTMENT"){
            $("#servicingdepartment").show();
            $("#fkStaffid").attr("disabled","disabled");
        }
    });
    
    $('#formmodal').on('shown.bs.modal', function () {
        $("input[name='fkPeriodid']").val($("#currentperiod").val());
        $("input[name='fkGroupid']").val($("#selectedclass").val());
    });
    
    
});
</script>
<div class="col col-md-10">
    <h3><?php echo $classes->getGroupName(); ?> modules: <?php echo $period->getTitle(); ?></h3>
    <hr>
    <div class="row">
    <div class="col col-md-4">
        
        

    </div>

    <div class="col col-md-8 text-right">
        <a data-toggle="modal" data-target="#formmodal" class="btn btn-primary">Allocate</a>
        <a href="<?php echo $this->url("administration",array("action"=>"classes")); ?>" class="btn btn-primary">Classes</a>
    </div>
</div>
    
    <hr>
    <table class="table table-bordered table-hover" id="searchable">
        <thead>
            <tr>
                <th>Module</th>
                <th>Parent module</th>
                <th>Exam(%)</th>
                <th>Course work(%)</th>
                <th>Is core</th>
                <th>Lecturer</th>
                <th width="60"></th>
                
            </tr>
        </thead>
        <tbody>
        <?php
        $counter = 1;
        foreach($modules as $module){
           $modulename      = (method_exists($module,'getFkModuleid'))?$module->getFkModuleid()->getModuleName()."( ".$module->getFkModuleid()->getModuleCode()." )": $module->getFkCcid()->getFkModuleid()->getModuleName()."( ".$module->getFkCcid()->getFkModuleid()->getModuleCode()." )";
           $cwkweighting    = (method_exists($module,'getCwkweight'))?$module->getCwkweight(): $module->getFkCcid()->getCwkweight();
           $examweighting   = (method_exists($module,'getExamweight'))?$module->getExamweight(): $module->getFkCcid()->getExamweight();
           $pcid            = (method_exists($module,'getPkCcid'))?$module->getPkCcid(): $module->getFkCcid()->getPkCcid(); 
           $moduleid        = (method_exists($module,'getFkModuleid'))?$module->getFkModuleid()->getPkModuleid(): $module->getFkCcid()->getFkModuleid()->getPkModuleid();
           $groupid         = (method_exists($module,'getFkGroupid'))?$module->getFkGroupid()->getPkGroupid(): $module->getFkCcid()->getFkGroupid()->getPkGroupid();
           $title           = (method_exists($module,'getFkPeriodid'))?$module->getFkPeriodid()->getTitle(): $module->getFkCcid()->getFkPeriodid()->getTitle();
           $iscore          = (method_exists($module,'getIscore'))?$module->getIscore(): $module->getFkCcid()->getIscore();
           $lecturer        = (!method_exists($module,'getFkStaffid'))?"Assign": $module->getFkStaffid()->getFkUserid()->getFirstname()." ".$module->getFkStaffid()->getFkUserid()->getSurname();
           $staffid         = (!method_exists($module,'getFkStaffid'))?"": $module->getFkStaffid()->getPkStaffid();
           
           if(method_exists($module,'getParentid')){
             $parentmodule  = ($module->getParentid() == NULL)?"":$module->getParentid()->getFkModuleid()->getModuleCode();
             $parentid      = ($module->getParentid() == NULL)?"":$module->getParentid()->getPkCcid();
           }else{
             $parentmodule  = ($module->getFkCcid()->getParentid() == NULL)?"":$module->getFkCcid()->getParentid()->getFkModuleid()->getModuleCode();  
             $parentid      = ($module->getFkCcid()->getParentid() == NULL)?"":$module->getFkCcid()->getParentid()->getPkCcid();
           } 
        ?>
        <tr>
            <td><span id="name<?php echo $counter; ?>"><?php echo $modulename; ?></span></td>
            <td><?php echo $parentmodule; ?></td>
            <td align="right" id="examweight<?php echo $counter; ?>"><?php echo $examweighting; ?></td>
            <input value="<?php echo $pcid; ?>" id="id<?php echo $counter; ?>" type="hidden" />
            <input value="<?php echo $parentid; ?>" id="parentid<?php echo $counter; ?>" type="hidden" />
            <input value="<?php echo $moduleid; ?>" id="moduleid<?php echo $counter; ?>" type="hidden" />
            <input value="<?php echo ($iscore)?"1":"0"; ?>" id="iscore<?php echo $counter; ?>" type="hidden" />
            <input value="<?php echo $groupid; ?>" id="group<?php echo $counter; ?>" type="hidden" />
            <td align="right" id="cwkweight<?php echo $counter; ?>"><?php echo $cwkweighting; ?></td>
            <input value="<?php echo $staffid; ?>" id="staffid<?php echo $counter; ?>" type="hidden" />
            <td><?php echo ($iscore)?"Yes":"No"; ?></td>
            <td><a data-toggle="modal" class="assign" data-target="#assignmodal" tabindex="<?php echo $counter; ?>" style="cursor:pointer"><?php echo $lecturer; ?></a></td>
            <td><div class="dropdown dropdown-menu-right pull-right">
                    <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-edit"></i> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                        <li role="presentation">
                            <a title="modify" id="<?php echo $counter; ?>" data-toggle="modal" data-target="#formmodal" style="cursor: pointer" >Modify</a>
                        </li>                     
                    </ul>
                </div>    </td>
            
        </tr>
        <?php
            $counter++;
        }
        ?>
        </tbody>
    </table>
    <div class="col ">
    <form class="form-inline" role="form">
        <input id="currentperiod" value="<?php echo $period->getPkPeriodid(); ?>" type="hidden" />
        <input id="selectedclass" value="<?php echo $classes->getPkGroupid(); ?>" type="hidden" />
        <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
    </form>    
    </div>
</div>
        