<div class="row">
<div class="col col-md-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group"><input class="form-control" placeholder="Search department" /></div>
                
            </div>
        </div>
    </div>
        <div class="col col-md-10">
            <div class="panel panel-default">
            <h3 class="page-header">Modules</h3>
            <div class="panel-body">
                
                <h4><?php echo $class->getClassName()."(".$class->getClassCode().")"; ?></h4>
                <hr>
                
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"classmoduleform","id"=>$class->getPkClassid())); ?>" class="btn btn-primary">Add New</a>&nbsp;<a href="<?php echo $this->url("administration",array("action"=>"departmentprograms","id"=>$class->getFkProgramid()->getFkdeptid()->getPkDeptid())); ?>" class="btn btn-warning">Back</a>  </div>
            <hr>
             <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success alert-dismissible"><?php echo $msg; ?></div>
            <?php
            }
            ?>
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Module</th>
        <th>Semester</th>
        <th>Exam Weight(%)</th>
        <th>CWK Weight(%)</th>
        
        <th>Is core</th>
        <th>Is project</th>
        <th width="50"></th>
      </tr>
    </thead>
    <tbody>
      
      <?php
      foreach($modules as $module){
      ?>
      <tr>
        <td><?php echo $module->getFkModuleid()->getModuleName()."( ".$module->getFkModuleid()->getModuleCode().")"; ?></td>
        <td><?php echo $module->getFkAcademicperiod()->getAcyr(); ?></td>
        <td><?php echo $module->getExweight(); ?></td>
        <td><?php echo $module->getCwkweight(); ?></td>
        
        <td><?php echo ($module->getIsCore()==1)?"Yes":"No"; ?></td>
        <td><?php echo ($module->getIsProject()==1)?"Yes":"No"; ?></td>
        <td><div class="dropdown dropdown-menu-right pull-right">
                    <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-edit"></i> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                        <li role="presentation">
                            <a title="modify" id="<?php //echo $counter; ?>" href="<?php echo $this->url("administration",array("action"=>"classmoduleform","id"=>$class->getPkClassid(),"subid"=>$module->getPkClassmoduleid())); ?>" style="cursor: pointer" ><i class="glyphicon glyphicon-edit"></i> Edit</a>
                        </li>
                        <li role="presentation">
                            <a  href="<?php //echo $this->url("administration",array("action"=>"lecturers","id"=>$department->getPkDepartmentid())); ?>"><i class="glyphicon glyphicon-remove"></i> Delete</a>
                        </li> 
                        <li role="presentation">
                            <a  href="<?php //echo $this->url("administration",array("action"=>"departmentprograms","id"=>$department->getPkDeptid())); ?>"><i class="glyphicon glyphicon-th-list"></i> Programmes</a>
                        </li> 
                    </ul>
                </div>    </td>
      </tr>
       <?php
      }
      ?>
    </tbody>
</table>
                <div class="col ">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label for="email">Show:</label>

<select class="form-control">
  <option>10</option>
  <option>20</option>
  <option>30</option>
  <option>50</option>
  <option>100</option>
</select> 
       
          
    </div>

      <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
                 
               </div>
            </div>
                </div>
        </div>
</div>
        