<div class="row">
<div class="col col-md-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <blockquote>
                   Quick links
                    
                </blockquote>
                <?php 

                $options= array('ulClass' => 'mtree transit');
                echo $this->navigation()->menu()->renderMenu("navigation",$options); ?>
            </div>
        </div>
    </div>
        <div class="col col-md-9">
            <div class="panel panel-default">
            <h3 class="page-header">Faculties</h3>
            <div class="panel-body">
                <div class="col text-right"><a href="<?php echo $this->url("administration",array("action"=>"facultyform")); ?>" class="btn btn-primary">Add New</a>  </div>
            <hr>
            <?php
            if(!empty($msg)){
            ?>
            <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <?php echo $msg; ?>
            </div>
            <?php
            }
            ?>
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Dean</th>
        <th width="50"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($faculties as $faculty){
      ?>

      <tr>
        <td><?php echo $faculty->getFacultyCode()?></td>
        <td><?php echo $faculty->getFacultyName()?></td>
        <td><?php echo (!empty($faculty->getFkStaffid()))?$faculty->getFkStaffid()->getFkUserid()->getFirstname()." ".$faculty->getFkStaffid()->getFkUserid()->getSurname():"Not assigned"; ?></td>
        <td><div class="dropdown dropdown-menu-right pull-right">
                    <button class="btn btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                        <i class="glyphicon glyphicon-edit"></i> Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                        <li role="presentation">
                            <a title="modify" id="<?php //echo $counter; ?>" href="<?php echo $this->url("administration",array("action"=>"facultyform","id"=>$faculty->getPkFacultyid())); ?>"  ><i class="glyphicon glyphicon-edit"></i> Edit</a>
                        </li>
                        <li role="presentation">
                            <a  href="<?php //echo $this->url("administration",array("action"=>"lecturers","id"=>$department->getPkDepartmentid())); ?>"><i class="glyphicon glyphicon-remove"></i> Delete</a>
                        </li> 
                        <li role="presentation">
                            <a  href="<?php echo $this->url("administration",array("action"=>"departments","id"=>$faculty->getPkFacultyid())); ?>"><i class="glyphicon glyphicon-list"></i> Departments</a>
                        </li> 
                    </ul>
                </div>    </td>
      </tr>
      <?php
      }
      ?>
    </tbody>
</table>
                <div class="col ">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label for="email">Show:</label>

<select class="form-control">
  <option>10</option>
  <option>20</option>
  <option>30</option>
  <option>50</option>
  <option>100</option>
</select> 
       
          
    </div>

      <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
                 
               </div>
            </div>
                </div>
        </div>
</div>
        